# This notebook has code pertaining to the cleaning and analyses of the data.

In [3]:
import pandas as pd

mvps = pd.read_csv(r"C:\Users\kannu\OneDrive\Documents\github repos\University\year-2\sem-4\ML\extras\project-2\Proto\mvps.csv")
mvps = mvps[["Player", "Year", "Pts Won", "Pts Max", "Share"]]
mvps

                Player  Year  Pts Won  Pts Max  Share
0       Michael Jordan  1991    891.0      960  0.928
1        Magic Johnson  1991    497.0      960  0.518
2       David Robinson  1991    476.0      960  0.496
3      Charles Barkley  1991    222.0      960  0.231
4          Karl Malone  1991    142.0      960  0.148
..                 ...   ...      ...      ...    ...
469  Russell Westbrook  2021      5.0     1010  0.005
470        Ben Simmons  2021      3.0     1010  0.003
471       James Harden  2021      1.0     1010  0.001
472       LeBron James  2021      1.0     1010  0.001
473      Kawhi Leonard  2021      1.0     1010  0.001

[474 rows x 5 columns]

In [26]:
players = pd.read_csv(r"C:\Users\kannu\OneDrive\Documents\github repos\University\year-2\sem-4\ML\extras\project-2\Proto\players.csv")
del players["Rk"]
del players["Unnamed: 0"]
players["Player"] = players["Player"].str.replace("*", "", regex = False)
players.head(5)

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,Alaa Abdelnaby,PF,22,POR,43,0,6.7,1.3,2.7,.474,...,0.6,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1,1991
1,Mahmoud Abdul-Rauf,PG,21,DEN,67,19,22.5,6.2,15.1,.413,...,0.5,1.3,1.8,3.1,0.8,0.1,1.6,2.2,14.1,1991
2,Mark Acres,C,28,ORL,68,0,19.3,1.6,3.1,.509,...,2.1,3.2,5.3,0.4,0.4,0.4,0.6,3.2,4.2,1991
3,Michael Adams,PG,28,DEN,66,66,35.5,8.5,21.5,.394,...,0.9,3.0,3.9,10.5,2.2,0.1,3.6,2.5,26.5,1991
4,Mark Aguirre,SF,31,DET,78,13,25.7,5.4,11.7,.462,...,1.7,3.1,4.8,1.8,0.6,0.3,1.6,2.7,14.2,1991

Combining the players and teams dataframes.

In [53]:
teams = pd.read_csv(r"C:\Users\kannu\OneDrive\Documents\github repos\University\year-2\sem-4\ML\extras\project-2\Proto\teams.csv")

# Here, this iterable command Checks for every row containing Division and deletes it
teams = teams[~teams["W"].str.contains("Division")].copy()
teams["Team"] = teams["Team"].str.replace("*", "", regex=False)
del teams["Unnamed: 0"]
teams

       W   L  W/L%    GB   PS/G   PA/G    SRS  Year                  Team
0     56  26  .683     â€”  111.5  105.7   5.22  1991        Boston Celtics
1     44  38  .537  12.0  105.4  105.6  -0.39  1991    Philadelphia 76ers
2     39  43  .476  17.0  103.1  103.3  -0.43  1991       New York Knicks
3     30  52  .366  26.0  101.4  106.4  -4.84  1991    Washington Bullets
4     26  56  .317  30.0  102.9  107.5  -4.53  1991       New Jersey Nets
...   ..  ..   ...   ...    ...    ...    ...   ...                   ...
1028  42  30  .583     â€”  112.4  110.2   2.26  2021      Dallas Mavericks
1029  38  34  .528   4.0  113.3  112.3   1.07  2021     Memphis Grizzlies
1030  33  39  .458   9.0  111.1  112.8  -1.58  2021     San Antonio Spurs
1031  31  41  .431  11.0  114.6  114.9  -0.20  2021  New Orleans Pelicans
1032  17  55  .236  25.0  108.8  116.7  -7.50  2021       Houston Rockets

[906 rows x 9 columns]

In [ ]:
sorted(teams["Team"].unique())
sorted(players["Tm"].unique())

nicknames = {}
with open(r"C:\Users\kannu\OneDrive\Documents\github repos\University\year-2\sem-4\ML\extras\project-2\Proto\nicknames.csv") as f:
    lines = f.readlines()
    for line in lines[1:]:
        abbrev, name = line.replace("\n", "").split(",")
        nicknames[abbrev] = name

nicknames

players["Team"] = players["Tm"].map(nicknames)

players

# Data Visualisation!
This is the part of the code where I'll be trying to perform EDA by plotting graphical representations of the data that I've scraped from [*basketball-reference.com*](https://basketball-reference.com). I will be using matplotlib.pyplot for this.

In [55]:
import seaborn as sns

sns.set_theme

bestWLPercentByYear = teams.groupby("Year").apply(lambda x: x.sort_values("W/L%", ascending=False).head(1))
bestWLPercentByYear

            W   L  W/L% GB   PS/G   PA/G    SRS  Year                    Team
Year
1991 23    63  19  .768  â€”  114.7  106.0   8.47  1991  Portland Trail Blazers
1992 38    67  15  .817  â€”  109.9   99.5  10.07  1992           Chicago Bulls
1993 83    62  20  .756  â€”  113.4  106.7   6.27  1993            Phoenix Suns
1994 113   63  19  .768  â€”  105.9   96.9   8.68  1994     Seattle SuperSonics
1995 136   62  20  .756  â€”  106.6  100.6   5.90  1995       San Antonio Spurs
1996 158   72  10  .878  â€”  105.2   92.9  11.80  1996           Chicago Bulls
1997 190   69  13  .841  â€”  103.1   92.3  10.70  1997           Chicago Bulls
1998 231   62  20  .756  â€”  101.0   94.4   5.73  1998               Utah Jazz
1999 264   37  13  .740  â€”   93.3   86.8   5.54  1999               Utah Jazz
2000 303   67  15  .817  â€”  100.8   92.3   8.41  2000      Los Angeles Lakers
2001 327   58  24  .707  â€”   96.2   88.4   7.92  2001       San Antonio Spurs
2002 367   61  21  .744  â€”  104.6   97.0   7.61  2002        Sacramento Kings
2003 392   60  22  .732  â€”  103.0   95.2   7.90  2003        Dallas Mavericks
2004 414   61  21  .744  â€”   91.4   85.6   4.93  2004          Indiana Pacers
2005 462   62  20  .756  â€”  110.4  103.3   7.08  2005            Phoenix Suns
2006 479   64  18  .780  â€”   96.8   90.2   6.24  2006         Detroit Pistons
2007 538   67  15  .817  â€”  100.0   92.8   7.28  2007        Dallas Mavericks
2008 543   66  16  .805  â€”  100.5   90.3   9.30  2008          Boston Celtics
2009 584   66  16  .805  â€”  100.3   91.4   8.68  2009     Cleveland Cavaliers
2010 619   61  21  .744  â€”  102.1   95.6   6.17  2010     Cleveland Cavaliers
2011 654   62  20  .756  â€”   98.6   91.3   6.53  2011           Chicago Bulls
2012 713   50  16  .758  â€”  103.7   96.5   7.28  2012       San Antonio Spurs
2013 730   66  16  .805  â€”  102.9   95.0   7.03  2013              Miami Heat
2014 783   62  20  .756  â€”  105.4   97.6   8.00  2014       San Antonio Spurs
2015 812   67  15  .817  â€”  110.0   99.9  10.01  2015   Golden State Warriors
2016 847   73   9  .890  â€”  114.9  104.1  10.38  2016   Golden State Warriors
2017 882   67  15  .817  â€”  115.9  104.3  11.35  2017   Golden State Warriors
2018 923   65  17  .793  â€”  112.4  103.9   8.21  2018         Houston Rockets
2019 934   60  22  .732  â€”  118.1  109.3   8.04  2019         Milwaukee Bucks
2020 969   56  17  .767  â€”  118.7  108.6   9.41  2020         Milwaukee Bucks
2021 1016  52  20  .722  â€”  116.4  107.2   8.97  2021               Utah Jazz